/*
 *   Copyright (c) 2023 Mikael Aboagye & Ultralight Inc.
 *   All rights reserved.

 *   Permission is hereby granted, free of charge, to any person obtaining a copy
 *   of this software and associated documentation files (the "Software"), to deal
 *   in the Software without restriction, including without limitation the rights
 *   to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *   copies of the Software, and to permit persons to whom the Software is
 *   furnished to do so, subject to the following conditions:

 *   The above copyright notice and this permission notice shall be included in all
 *   copies or substantial portions of the Software.

 *   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *   IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *   FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 *   AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *   LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *   SOFTWARE.
 */

#pragma once

// CoreMinimal must be first for UE projects
#include "CoreMinimal.h"
// It's good practice to include the ThirdParty includes after UE headers,
// especially if they might have conflicting macro definitions or common names.
#include <Ultralight/platform/FileSystem.h>
// This define likely comes from the UltralightUELibrary module, ensure path is correct if it's a public header.
// Assuming ULUEDefines.h is correctly located in UltralightUELibrary's public include path.
// #include "ULUEDefines.h" // Potentially problematic if it defines ULTRALIGHTUE_API or if not needed here.
                             // ULTRALIGHTUE_API should be auto-generated by UBT for this module.
                             // If ULUEDefines.h is for ULTRALIGHTUELIBRARY_API, it might still be needed if types from that lib are used.
                             // For now, commenting out to see if CoreMinimal.h and UBT's auto-generation of ULTRALIGHTUE_API is sufficient.

namespace ultralightue
{
    // Temporarily removing ULTRALIGHTUE_API from enum class to isolate issues.
    // If ULTRALIGHTUE_API itself is problematic, this will help confirm.
    enum class FSAccess : uint8_t
    {
        FSA_Native = 0x0001,  /// Native UE FileSystem, should be used with editor modules.
        FSA_Package = 0x0002, /// Package FileSystem, should be used at runtime.
    };

    /// @brief Unreal Engine implementation of Ultralight's FileSystem.
    /*
     * NOTE: This is a internal class. you should not really be using this, unless you have a special filesystem to set.
     * HOW TO USE: SetFSAccess if you are using the native file system, or reading through package files, then provide to ULUEHandler.
     */
    class ULTRALIGHTUE_API ULUEFileSystem : public ultralight::FileSystem
    {
    public:
        void SetFSAccess(FSAccess InAccessPattern);
        ULUEFileSystem();

        // It's good practice to explicitly mark the destructor as virtual if the base class has a virtual destructor.
        // And ensure it's defaulted or properly implemented.
        virtual ~ULUEFileSystem() override; // Changed from UEFileSystem to ULUEFileSystem

        virtual bool FileExists(const ultralight::String &path) override;
        virtual bool GetFileSize(ultralight::FileHandle handle, int64_t &result) override;

        virtual ultralight::FileHandle OpenFile(const ultralight::String &path, bool open_for_writing) override;

        virtual void CloseFile(ultralight::FileHandle &handle) override;

        // Changed char* to uint8* as Read expects uint8* in UE IFileHandle, and ultralight::FileSystem::ReadFromFile expects char*.
        // This might require a reinterpret_cast in the implementation if the underlying system truly uses different types.
        // For now, sticking to ultralight's definition.
        virtual int64_t ReadFromFile(ultralight::FileHandle handle, char *data, int64_t length) override; // Return type changed to int64_t to match Ultralight 1.3+

        virtual bool GetFileMimeType(const ultralight::String &path, ultralight::String &result) override;

        virtual bool GetFileCharset(const ultralight::String &path, ultralight::String &result) override;

        virtual bool GetFileCreationTime(const ultralight::String &path, int64_t &result) override;
        virtual bool GetFileLastModificationTime(const ultralight::String &path, int64_t &result) override;

    private:
        FString MapPath(const ultralight::String &path);
    // private: // This was duplicated, removing one
        FString BaseDirectory;
        ultralightue::FSAccess m_access = FSAccess::FSA_Native;
    };
}